language: go
sudo: false
before_install:
  - mkdir -p $HOME/gopath/src/github.com/huaweicloud/golangsdk
  - rsync -az ${TRAVIS_BUILD_DIR}/ $HOME/gopath/src/github.com/huaweicloud/golangsdk/
  - export TRAVIS_BUILD_DIR=$HOME/gopath/src/github.com/huaweicloud/golangsdk
  - cd $HOME/gopath/src/github.com/huaweicloud/golangsdk
install:
- go get golang.org/x/crypto/ssh
- go get github.com/xioxu/golangsdk
- go get github.com/wadey/gocovmerge
- go get github.com/mattn/goveralls
- go get golang.org/x/tools/cmd/goimports
go:
- 1.8
- tip
env:
  global:
  - secure: "5XfjlctyrfCccnP8hSUFv3bmGsYTS912L"
before_script:
- go vet ./...
script:
- ./script/coverage
- ./script/format
after_success:
- $HOME/gopath/bin/goveralls -service=travis-ci -coverprofile=cover.out
